### ISSUE TITLE
Vercel Page 404

### ISSUE THREAD

**Issue by ryoppippi** [mirko-san/mclock#10]
面白いページを作っていただきありがとうございます。
僕もsvelte好きなので、記事を楽しく拝読させていただきました。

Vercelのページが404になっていますので、報告させていただきました

**Comment by mirko-san** [comment]
@ryoppippi

感想ありがとうございます。
記事の公開後に行った Web Components への対応のせいで、 Vercel の画面が閲覧できなくなっていたようです。
https://github.com/mirko-san/mclock/pull/8

こちらおかげさまで対応しておきましたので、 close いたしました。
ご報告ありがとうございました！
